/**
 * Razorpay Payment Service
 * Production-ready integration for Razorpay.
 * All functions use the shared axios instance from api.ts.
 */
import { api } from './api';

/**
 * Create a Razorpay order for one-time or subscription entry payments.
 * The backend will determine the amount based on the plan.
 * @param plan - The subscription plan identifier (e.g., 'premium', 'premium_annual').
 * @param userId - The ID of the user creating the order.
 * @param notes - Optional metadata to associate with the order.
 */
export const createRazorpayOrder = async (
  plan: string,
  userId: string,
  notes: Record<string, any> = {}
) => {
  try {
    console.log(`[RazorpayService] Creating order for plan "${plan}" for user ${userId}`);
    const response = await api.post('/payment/create-order/', {
      plan: plan,
      user_id: userId,
      notes,
    });
    return response.data;
  } catch (error: any) {
    console.error('[RazorpayService] Failed to create order:', error.response?.data || error.message);
    throw new Error(error.response?.data?.error || error.message || 'Failed to create Razorpay order');
  }
};

/**
 * Verify payment on the backend using the Razorpay signature.
 * This is a critical security step to confirm payment authenticity.
 * @param orderId - The Razorpay order ID.
 * @param paymentId - The Razorpay payment ID.
 * @param signature - The signature generated by Razorpay.
 */
export const verifyRazorpayPayment = async (
  orderId: string,
  paymentId: string,
  signature: string
) => {
  try {
    console.log(`[RazorpayService] Verifying payment for order ${orderId}`);
    const response = await api.post('/payment/verify/', {
      razorpay_order_id: orderId,
      razorpay_payment_id: paymentId,
      razorpay_signature: signature,
    });
    console.log('[RazorpayService] Payment verification successful.');
    return response.data;
  } catch (error: any) {
    console.error('[RazorpayService] Failed to verify payment:', error.response?.data || error.message);
    throw new Error(error.response?.data?.error || error.message || 'Failed to verify payment');
  }
};

/**
 * Fetch the public Razorpay key from the backend.
 * This key is required to initialize the Razorpay checkout.
 */
export const getRazorpayKey = async () => {
  try {
    console.log('[RazorpayService] Fetching Razorpay Key ID...');
    const response = await api.get('/payment/razorpay-key/');
    console.log('[RazorpayService] Razorpay Key ID fetched successfully.');
    return response.data?.key_id as string;
  } catch (error: any) {
    console.error('[RazorpayService] Failed to load Razorpay key:', error.response?.data || error.message);
    throw new Error(error.response?.data?.error || error.message || 'Failed to load Razorpay key');
  }
};